name: integration test
on:
  push:
    branches: 
     -master

env:
  K6_CLOUD_TOKEN: ${{ secrets.K6_CLOUD_TOKEN }} 
  URL: ${{ secrets.URL }}

jobs:
  k6_cloud_test: 
    name: k6 cloud test run
    runs-on: ubuntu-latest
    container: docker://grafana/k6:latest

    env:
      VARIABLE: test

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cloud k6 test
        run: k6 run "./$VARIABLE.js"

